import org.gradle.api.artifacts.DependencyResolveDetails

def groupName = 'org.nrg'
def artifactName = 'grxnat'
def buildVersion = '1.19'

group groupName
version buildVersion

apply plugin: 'groovy'
apply plugin: 'java'
apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply plugin: 'idea'
apply plugin: 'eclipse'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'io.freefair.aspectj.post-compile-weaving'

def vBom = '3.1'
def vTestUtils = '2.5'

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:1.0.3.RELEASE'
        classpath 'io.freefair.gradle:aspectj-plugin:5.3.0'
    }
}

dependencyManagement {
    imports {
        mavenBom "org.nrg:test_dependencies:${vBom}"
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://nrgxnat.jfrog.io/nrgxnat/libs-release' }
    maven { url 'https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot' }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

configurations {
    api.extendsFrom(apiAndInclude)

    all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.codehaus.groovy') {
                details.useVersion dependencyManagement.importedProperties['vGroovy']
                details.because "needed by rest-assured>=4.3"
            }
        }
    }
}

dependencies {
    implementation(group: 'org.codehaus.groovy', name: 'groovy-all', version: dependencyManagement.importedProperties['vGroovy'], ext: 'pom')
    apiAndInclude('org.apache.commons:commons-lang3')
    apiAndInclude('commons-io:commons-io')
    apiAndInclude('com.fasterxml.jackson.core:jackson-annotations')
    apiAndInclude('com.fasterxml.jackson.core:jackson-core')
    apiAndInclude('com.fasterxml.jackson.core:jackson-databind')
    apiAndInclude('com.fasterxml.jackson.dataformat:jackson-dataformat-yaml')
    apiAndInclude('com.fasterxml.jackson.datatype:jackson-datatype-hibernate4')
    apiAndInclude('org.hibernate:hibernate-core')
    apiAndInclude('org.reflections:reflections')
    apiAndInclude('io.rest-assured:rest-assured') {
        exclude(group: 'org.codehaus.groovy', module: '*')
    }
    apiAndInclude('org.slf4j:slf4j-log4j12')
    apiAndInclude("org.nrg:test_utils:${vTestUtils}")
    apiAndInclude('org.codehaus.gpars:gpars')
    apiAndInclude('org.dcm4che.tool:dcm4che-tool-storescu')
    apiAndInclude('org.aspectj:aspectjweaver')
    apiAndInclude('org.aspectj:aspectjrt')

    testImplementation 'org.testng:testng'
}

test {
    useTestNG {}
}

jar {
    from sourceSets.main.allSource

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId groupName
            artifactId artifactName
            version buildVersion

            from components.java

            pom.withXml {
                def root = asNode()
                root.appendNode('name', 'grxnat')
                root.appendNode('url', 'https://bitbucket.org/xnatdev/grxnat')
                root.appendNode('inceptionYear', '2017')

                def scm = root.appendNode('scm')
                scm.appendNode('url', 'https://bitbucket.org/xnatdev/grxnat')
                scm.appendNode('connection', 'https://bitbucket.org/xnatdev/grxnat')
                scm.appendNode('developerConnection', 'scm:git://bitbucket.org/xnatdev/grxnat.git')

                def developers = root.appendNode('developers')

                def charlie = developers.appendNode('developer')
                charlie.appendNode('id', 'grepStar')
                charlie.appendNode('name', 'Charlie Moore')
                charlie.appendNode('email', 'moore.c@wustl.edu')
            }
        }
    }
    repositories {
        maven {
            credentials {
                // These properties must be set in the ~/.gradle/gradle.properties file or passed on the Gradle command
                // line in the form -PrepoUsername=foo -PrepoPassword=bar.
                username propertyWithDefault('repoUsername', 'username') as String
                password propertyWithDefault('repoPassword', 'password') as String
            }
            if (project.version.endsWith('-SNAPSHOT')) {
                url 'https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot-local'
            } else {
                url 'https://nrgxnat.jfrog.io/nrgxnat/libs-release-local'
            }
        }
    }
}

task fatJar(type: Jar) {
    zip64 true
    classifier = 'fat'
    from {
        configurations.apiAndInclude.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }
    with jar
}

def propertyWithDefault(String property, Object value) {
    hasProperty(property) ? getProperty(property) : value
}

defaultTasks 'clean', 'jar', 'test', 'publishMavenJavaPublicationToMavenRepository', 'publishToMavenLocal'
