package org.nrg.xnat.pogo.events

enum EventStepStatus {

    OBJECT_FILTER_MISMATCH_HALT,
    EVENT_TRIGGERED,
    EVENT_DETECTED,
    SUBSCRIPTION_TRIGGERED,
    OBJECT_SERIALIZED,
    OBJECT_FILTERED,
    RESOLVING_ATTRIBUTES,
    ACTION_CALLED,
    ACTION_STEP,
    ACTION_COMPLETE

}